config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'home#index'

  resources :movie_categories
  resources :movies
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
# frozen_string_literal: true

class Movie < ApplicationRecord
  belongs_to :movie_category
end

app/models/movie_category.rb
# frozen_string_literal: true

class MovieCategory < ApplicationRecord
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
# frozen_string_literal: true

# This is the home page controller
class HomeController < ApplicationController
  def index; end
end

app/controllers/movie_categories_controller.rb
# frozen_string_literal: true

# This is the movie categories controller
class MovieCategoriesController < ApplicationController
  def index
    @movie_categories = MovieCategory.all
  end
end

app/controllers/movies_controller.rb
# frozen_string_literal: true

# This is the movies controller
class MoviesController < ApplicationController
  def index
    @movies = Movie.all
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/home/index.html.erb
<h1>Rent Movies</h1>
<h2>Seja bem-vindo à sua plataforma de aluguel e revisão de filmes!</h2>

<h3>
    <%= link_to 'Categorias', movie_categories_path %>
    <%= link_to 'Todos os filmes', movies_path %>
</h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BrickBusters</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/movie_categories/index.html.erb
<% @movie_categories.each do |category| %>
    <%= category.name %>
<% end %>

app/views/movies/index.html.erb
<% @movies.each do |movie| %>
    <%= movie.name %>
<% end %>